var arrayCarrousel=document.querySelectorAll("[carrousel-element]");if(arrayCarrousel.length>0){arrayCarrousel.forEach((carrouselElement)=>{var carrousel={element:carrouselElement,container:carrouselElement.querySelector("#carrousel-container"),lista:carrouselElement.querySelector("#carrousel-container ul"),imagemDestaque:carrouselElement.querySelector("#carousel .imagem-destacada"),total:carrouselElement.querySelector("#carrousel-container ul").childElementCount,marginRightItems:16,ultimoVisivel:4,numClones:0,numVisivel:4,atual:0,transitionTime:500,getPosToCenter:()=>{return(window.screen.width/2)-(carrousel.getElementActiveWidth()/2)},getSlideAtual:()=>{return carrousel.element.querySelectorAll(".carousel-item")[carrousel.atual+carrousel.numClones]},getElementWidth:()=>{return((carrousel.container.offsetWidth)/carrousel.numVisivel)-16},mostrarProximo:()=>{if(!carrousel.isInfinite()&&carrousel.atual===carrousel.total-1){return}
carrousel.atual+=1;carrousel.processoDeMover()},mostrarAnterior:()=>{if(!carrousel.isInfinite()&&cmostrarCarrousel.atual===0){return}
carrousel.atual-=1;carrousel.processoDeMover()},mostrarClicado:(event)=>{var botao=event.target;while(botao.tagName!=="LI"&&botao!==document.body){botao=botao.parentNode}
var index=parseInt(botao.getAttribute("data-index"));carrousel.atual=index;carrousel.processoDeMover()},processoDeMover:()=>{destacarImagemDoSlideAtual();if(carrousel.isInfinite()){mover(carrousel.atual);retirarOnclickBtns();setTimeout(()=>{verificarSlideAtualClone();definirOnclickBtns()},carrousel.transitionTime)}},isInfinite:()=>{return carrousel.total>=carrousel.numVisivel},initialize:()=>{if(carrousel.isInfinite()){definirQtdeClone();criarClones()}
definirIndexDosItems();destacarImagemDoSlideAtual();definirOnclickItems();mover(0);window.addEventListener("load",definirLarguraItems);window.addEventListener("load",definirOnclickBtns);window.addEventListener("afterprint",definirLarguraItems);window.addEventListener("afterprint",definirOnclickBtns);window.addEventListener("resize",()=>{definirLarguraItems();mover(carrousel.atual)})}}
carrousel.initialize();function mover(index){index+=carrousel.numClones;var translateX=(carrousel.getElementWidth()+carrousel.marginRightItems)*index;translateX*=-1;carrousel.lista.style="transform : translate3d("+translateX+"px, 0, 0);"}
function moverSemAnimacao(index){index+=carrousel.numClones;var translateX=(carrousel.getElementWidth()+carrousel.marginRightItems)*index;translateX*=-1;carrousel.lista.style="transform : translate3d("+translateX+"px, 0, 0); transition-duration : 0s !important;"}
function verificarSlideAtualClone(){if(carrousel.atual<0){carrousel.atual=carrousel.total+carrousel.atual;moverSemAnimacao(carrousel.atual)}
else if(carrousel.atual>carrousel.total-1){carrousel.atual=carrousel.atual-carrousel.total;moverSemAnimacao(carrousel.atual)}}
function definir_qtde_visivel(){if(window.screen.width<700){carrousel.numVisivel=1}else if(window.screen.width>=700&&window.screen.width<900){carrousel.numVisivel=2}else if(window.screen.width>=900){carrousel.numVisivel=3}}
function definirQtdeClone(){carrousel.numClones=carrousel.total}
function criarClones(){var qtdeClones=carrousel.numClones;var arraySlides=carrousel.container.querySelectorAll("li");var arraySlidesEClones=[];for(var i=carrousel.total-qtdeClones;i<carrousel.total;i++){var slidet=arraySlides[i].cloneNode(!0);slidet.classList.add("cloned");arraySlidesEClones.push(slidet)}
arraySlides.forEach((slide)=>{var novoSlide=slide.cloneNode(!0);arraySlidesEClones.push(novoSlide)});for(var i=0;i<qtdeClones;i++){var slide=arraySlides[i].cloneNode(!0);slide.classList.add("cloned");arraySlidesEClones.push(slide)}
carrousel.container.querySelector("ul").innerHTML="";arraySlidesEClones.forEach((slide)=>{carrousel.container.querySelector("ul").appendChild(slide)})}
function destacarImagemDoSlideAtual(){var newImage=carrousel.getSlideAtual().querySelector("img").cloneNode(!0);var imagemDestacada=carrousel.imagemDestaque.querySelector("img");if(imagemDestacada!==null&imagemDestacada!=="undefined"){imagemDestacada.classList.add("hide");setTimeout(()=>{imagemDestacada.remove()},carrousel.transitionTime);carrousel.imagemDestaque.insertBefore(newImage,imagemDestacada)}
else{carrousel.imagemDestaque.appendChild(newImage)}}
function definirLarguraItems(){var items=carrousel.element.querySelectorAll(".carousel-item");items.forEach((item)=>{item.style.width=carrousel.getElementWidth()+"px"})}
function definirIndexDosItems(){var items=carrousel.container.querySelectorAll("li");var index=0-(carrousel.numClones);items.forEach((item)=>{item.setAttribute("data-index",index);index++})}
function definirOnclickItems(){var items=carrousel.element.querySelectorAll(".carousel-item");items.forEach((item)=>{var oc=()=>{carrousel.mostrarClicado(item)};item.addEventListener("click",carrousel.mostrarClicado)})}
function definir_largura_items_sem_animacao(){var items=carrousel.element.querySelectorAll(".carousel-item");items.forEach((item)=>{item.style="width : "+carrousel.getElementWidth()+"px; transition-duration : 0s !important;";setTimeout(()=>{item.style="width : "+carrousel.getElementWidth()+"px"},10)})}
function definir_altura_min(){carrousel.container.querySelector("ul").style.minHeight=carrousel.element.offsetHeight+"px"}
function onclicks(Evt){var botao=Evt.target;while(!botao.classList.contains("btn")){botao=botao.parentNode}
if(botao.getAttribute("data-target")==="previous"){carrousel.mostrarAnterior()}
else if(botao.getAttribute("data-target")==="next"){carrousel.mostrarProximo()}}
function retirarOnclickBtns(){var btns=carrousel.element.querySelectorAll(".btn");btns.forEach((btn)=>{btn.removeEventListener("click",onclicks)})}
function definirOnclickBtns(){var btns=carrousel.element.querySelectorAll(".btn");btns.forEach((btn)=>{btn.addEventListener("click",onclicks)})}})}